Revamp - Run Containers as Non-Root

diff --git a/docker/docker-base-entrypoint b/docker/docker-base-entrypoint
--- a/docker/docker-base-entrypoint
+++ b/docker/docker-base-entrypoint
@@ -13,20 +13,18 @@ set -eu
   # --------------------------------------------------------------------------------------------------------------------
 
   # !-- We want to only print in logs if something wrong happened, hence how below code is written. --!
-  echo "► Running composer's post-install-cmd..."
-  error=$(composer run-script --no-interaction post-install-cmd 2>&1)  \
-  || if [ $? -ne 0 ]; then printf "%s \nerror running composer post-install-cmd script: " "$error"; exit 1; fi
-  echo "✔ Successful"
+  if (composer run-script -l 2> /dev/null | command grep --silent "post-install-cmd" > /dev/null)
+  then
+      echo "► Running composer's post-install-cmd..."
+      error=$(composer run-script --no-interaction post-install-cmd 2>&1)  \
+      || if [ $? -ne 0 ]; then printf "%s \nerror running composer post-install-cmd script: " "$error"; exit 1; fi
+      echo "✔ Successful"
+  fi
 
   # Run custom ad-hoc post-deployment script
   echo "► Running custom post deployment script..."
   error=$(docker-base-post-deployment 2>&1)  \
   || if [ $? -ne 0 ]; then printf "%s \nerror running post-deployment script: " "$error"; exit 1; fi
-  echo "✔ Successful"
-
-  # Permissions for var directory (generated by post-install-cmd)
-  echo "► Adjusting Permissions... "
-  chown -R www-data:www-data var
   echo "✔ Successful"
 
 )
